### ISSUE TITLE
Create a main menu page

### ISSUE THREAD

**Issue by panpan2557** [SSD2015/Team2Big2Slim#10]
Only visual main menu will be implemented.

**Comment by momogame** [comment]
First version , I implement it as a button to represent a menu option at the top and group's project. Since the menu option and group's project is clickable (menu option shows an option, and group's project link to a project page) , so I use it as a empty button for now.

![it1_main-menu1](https://cloud.githubusercontent.com/assets/6860907/6435094/9a618776-c0c8-11e4-8650-fb626c2f522b.jpg)

**Comment by momogame** [comment]
Second version after discuss with a teammate, we agree to change these button to an image. 
-Group's project
Since a group's project button from previous version, actually show a group banner image from each group, so it might be better to implement as a image.

-Menu option( menu bar)
The top bar actually consist of a clock(left side) and option(right side), so only a option is clickable (from what mockup shown). So we change this menu bar into image as well, and will set the option area to be clickable in the future.

Right now, all the image can't be clicked.

![it1_main-menu2](https://cloud.githubusercontent.com/assets/6860907/6435315/479cab82-c0ce-11e4-8ea6-95d8de739a28.jpg)

**Comment by panpan2557** [comment]
![screen shot 2558-03-04 at 5 43 40 pm](https://cloud.githubusercontent.com/assets/6860112/6482195/37f8bb2a-c296-11e4-96cf-0efee4222e32.png)

Finish with merging my work, 
- add option button 
- fix every elements size to viewer's maximum size
- fix the position of top panel
