### ISSUE TITLE
Feedback on Iteration Plan EL1

### ISSUE THREAD

**Issue by mapfap** [SSD2015/Team2Big2Slim#19]
From [Iteration Plan](https://github.com/SSD2015/Team2Big2Slim/blob/master/ITPlanEL1.md),
- 'Option button and Project Banner is touchable and will show the dump page'. What is dump page?
- project can be vote -> voted
- runable -> runnable
- "Create an application for eXceed vote" maybe too vague? ...or do you mean build the distributable file like .apk?
- Don't forget to assign task to members.

**Comment by panpan2557** [comment]
Thank you, we will fix it soon

**Comment by jbrucker** [comment]
> The project can be vote by touching "vote button" inside "Option menu".

English: you put "Vote button" inside quotes, implying that there will be a button named:  `Vote button`

Wording:  **too much UI specific detail**

> touching "vote button".  

What if the user doesn't have a touchscreen? He can touch it all day, but nothing will happen.

> inside "Option menu". 
- What Option menu?  This application must be easy to use. Menus require effort to familiarize.
- Design issue: voting is the main function, hence Vote should be readily visible, not in menu.

**Comment by jbrucker** [comment]
panpan2557 wrote:

>  Thank you, we will fix it soon

That was 2 days ago and you haven't done what Saran suggested.
Its only a few minutes to edit, so why not fix it immediately?

**Comment by panpan2557** [comment]
I'm sorry, finish with fixing it now.

For our voting, users can make a vote after they rate (give the scores in each criteria) to every groups.
We have discussed about this issue too, whether we will put the vote button inside option menu or not. Because, if the vote button is outside so in option menu we will only have camera and logout.
It can cause another issue, is option menu meaningful (i mean why there is option menu there if there are only a few things and require another 1 click/touch) and also if all buttons, camera, vote and logout, lie out at the top which has the timer on the top left. We think that it will somehow make the timer smaller. And according to our design, we will try to have many colour effects and a little guidance that will attract and guide the users as much as possible.
However, in the first iteration we will try to make it simple and put it in main menu. Our design is just some assumption + imagination to make it easy to use with plain UI. If it causes any inconvenient usage we will change it for sure.

Thank you very much for your suggestions and sorry for the late correction.
