### ISSUE TITLE
Login page (UI)

### ISSUE THREAD

**Issue by panpan2557** [SSD2015/Team2Big2Slim#40]

**Comment by Sompatbu** [comment]
Depend on : [Link users with database](https://github.com/SSD2015/Team2Big2Slim/issues/41)

**Comment by momogame** [comment]
Here is the first version of login page that will be use for this iteration.
The page still plain. The text box will receive a username and password of user.
Right now, only username as "admin" and password as "admin" will have a permission to proceed on to next page after click sign in button. Otherwise, page will be refresh.

![login](https://cloud.githubusercontent.com/assets/6860907/6822010/f2d56a96-d30e-11e4-8c73-948c5d04763f.jpg)

**Comment by momogame** [comment]
Update: Login is now link with a database. Only a username and password which is store in database will have a permission to access.

**Comment by panpan2557** [comment]
Update Login UI but not finish with it
